name: Backend CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Start backend and DB containers
        run: |
          docker-compose -f docker-compose.yml up --build -d db backend
          sleep 30

      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest backend/tests/test_services.py
          coverage xml

      - name: Stop containers
        run: docker-compose down

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
